### ISSUE TITLE
貌似打包不了trojan-cli.zip，试了好多次了

### ISSUE THREAD

**Issue by acegank** [ShawnZhang31/troooojan-install#1]
Archive:  trojan-cli.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of trojan-cli.zip or
        trojan-cli.zip.zip, and cannot find trojan-cli.zip.ZIP, period.
cp: cannot create regular file ‘/usr/src/trojan-cli/fullchain.cer’: No such file or directory
./trojan_centos7.sh: line 87: /usr/src/trojan-cli/config.json: No such file or directory
./trojan_centos7.sh: line 164: cd: /usr/src/trojan-cli/: No such file or directory

**Comment by acegank** [comment]
兄弟你脚本安装的下载地址错了吧

**Comment by ShawnZhang31** [comment]
> 兄弟你脚本安装的下载地址错了吧

你好，问题已修复，谢谢反馈

**Comment by ShawnZhang31** [comment]
> Archive: trojan-cli.zip
> End-of-central-directory signature not found. Either this file is not
> a zipfile, or it constitutes one disk of a multi-part archive. In the
> latter case the central directory and zipfile comment will be found on
> the last disk(s) of this archive.
> unzip: cannot find zipfile directory in one of trojan-cli.zip or
> trojan-cli.zip.zip, and cannot find trojan-cli.zip.ZIP, period.
> cp: cannot create regular file ‘/usr/src/trojan-cli/fullchain.cer’: No such file or directory
> ./trojan_centos7.sh: line 87: /usr/src/trojan-cli/config.json: No such file or directory
> ./trojan_centos7.sh: line 164: cd: /usr/src/trojan-cli/: No such file or directory

This bug has been fixed, thanks for your reply! See ShawnZhang31@679183c3adc22831c78b3b60905f3a1bcb787f63
